### ISSUE TITLE
How to deal with unserializable task?

### ISSUE THREAD

**Issue by oeway** [millerdev/WorQ#3]
Hi,
I have some task contains some object which is not pickleable, how to deal with that? Thank you.

**Comment by llazzaro** [comment]
Are you using multi process?

**Comment by oeway** [comment]
Yes.

**Comment by millerdev** [comment]
You'll need to save it in some other persistent storage such as a database, and then load it in the task. Anything that cannot be pickled cannot be passed to a task.
