### ISSUE TITLE
Python 3.5: Cannot import name 'reduce_connection'

### ISSUE THREAD

**Issue by flyte** [millerdev/WorQ#5]
Hi, I get this error on Python 3.5, as that module doesn't exist:

```python
Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from worq.pool.process import WorkerPool
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/flyte/.virtualenvs/mqtt-videocap/lib/python3.5/site-packages/worq/pool/process.py", line 42, in <module>
    from multiprocessing.reduction import reduce_connection, rebuild_connection
ImportError: cannot import name 'reduce_connection'
```

**Comment by millerdev** [comment]
Hi @flyte, thanks for reporting the issue. Looks like the internals of the process pool need to be refactored for Python 3. I'm not sure if or when I'll ever get around to that. Pull requests accepted.

**Comment by snguyenthanh** [comment]
Hi @millerdev, 
I'm able to trace back the problem. 
The release of [WorQ](https://github.com/millerdev/WorQ) on (PyPi)[https://pypi.python.org/pypi/WorQ] import `reduce_connection` from the unsupported package of Python 3.

In worq.pool.process in this repo, line 40:
```
...
from multiprocessing import Pipe, cpu_count, current_process
from multiprocessing.process import AuthenticationString
try:
    from cPickle import dump, load, HIGHEST_PROTOCOL, PicklingError
    from Queue import Empty, Queue as ThreadQueue
    from multiprocessing.reduction import reduce_connection, rebuild_connection
except ImportError:
    # python 3 imports
    from pickle import dump, load, HIGHEST_PROTOCOL, PicklingError
    from queue import Empty, Queue as ThreadQueue
    from multiprocessing.connection import reduce_connection, rebuild_connection
...
``

In the Worq [release](https://pypi.python.org/pypi/WorQ) on Pypi, line 42:
```
...
from multiprocessing import Pipe, cpu_count, current_process
from multiprocessing.process import AuthenticationString
from multiprocessing.reduction import reduce_connection, rebuild_connection
try:
    from cPickle import dump, load, HIGHEST_PROTOCOL, PicklingError
    from Queue import Empty, Queue as ThreadQueue
except ImportError:
    from pickle import dump, load, HIGHEST_PROTOCOL, PicklingError
    from queue import Empty, Queue as ThreadQueue
...
```
As you see, `reduce_connection` and `rebuild_connection` in the release are not imported from `connection` when running in Python 3.

This could be solved manually by going to `/site-packages/worq/pool/process.py` and replace line 42-48 with code from the repo.

**Comment by millerdev** [comment]
@snguyenthanh thanks for reminding me to do this. Should be fixed now.

https://pypi.python.org/pypi/WorQ/1.1.1
